### ISSUE TITLE
How do it can support for Kafka's producer?

### ISSUE THREAD

**Issue by elkan1788** [takebayashi/fluent-plugin-avro#3]
Hi, thanks for your contribution. Also I had read your code but not found it support Kafka's producer , also it seems not support Avro block message. So I want to upgrade these features what should I do? Thanks.

**Comment by takebayashi** [comment]
Are you using `fluent-plugin-kafka`?
Its `kafka_buffered` plugin supports custom formatters by specifying `output_data_type` parameter. You can produce Avro messages to Kafka by combining that and `fluent-plugin-avro`.
